import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import SumaTypeScript from "@/components/sumaTypeScript";
import SumaJavaScript from "@/components/sumaJavaScript";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>JavaScript vs TypeScript</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Ejemplo de Componentes que Suman JavaScrip vs TypeScript</h1>
        <SumaJavaScript />
        <SumaTypeScript sumando1={3} sumando2={2} />
      </main>

      <style jsx>{`
        h1 {
          text-align: center;
          margin: 2rem;
        }
      `}</style>
    </>
  );
}
